/* Autogenerated by png2wx.pl on Sat May 26 14:21:45 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>		
#include "dashboard_pi.h"

extern void initialize_images(void);

#ifdef _TACTICSPI_H_
extern wxBitmap *_img_dashboard_tactics_pi; // if needed, separate icons can be created...
extern wxBitmap *_img_dashboard_tactics;    // ... if built-in dashboard has a copyright.
#else
extern wxBitmap *_img_dashboard_pi;
extern wxBitmap *_img_dashboard;
#endif // _TACTICSPI_H_
extern wxBitmap *_img_dial;
extern wxBitmap *_img_instrument;
extern wxBitmap *_img_minus;
extern wxBitmap *_img_plus;

#ifdef PLUGIN_USE_SVG
#ifdef _TACTICSPI_H_
extern wxString _svg_dashboard_tactics;
extern wxString _svg_dashboard_tactics_rollover;
extern wxString _svg_dashboard_tactics_toggled;
#else
extern wxString _svg_dashboard;
extern wxString _svg_dashboard_rollover;
extern wxString _svg_dashboard_toggled;
#endif // _TACTICSPI_H_
#endif //  PLUGIN_USE_SVG

#endif /* ICONS_H */
