/* Autogenerated by png2wx.pl on Sat May 26 14:21:45 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_dashboard_tactics_pi; // if needed, separate icons can be created...
extern wxBitmap *_img_dashboard_tactics;    // ... if built-in dashboard has a copyright.
extern wxBitmap *_img_dial;
extern wxBitmap *_img_instrument;
extern wxBitmap *_img_minus;
extern wxBitmap *_img_plus;

#ifdef OCPN_USE_SVG
extern wxString _svg_dashboard_tactics;
extern wxString _svg_dashboard_tactics_rollover;
extern wxString _svg_dashboard_tactics_toggled;
#endif //  OCPN_USE_SVG

extern const unsigned char btnstartrec_png[1170];
extern const unsigned char btnstoprec_png[1005];
extern const unsigned char btnbackstop_png[1121];
extern const unsigned char btneject_png[1139];

#endif /* ICONS_H */
