/* Autogenerated by png2wx.pl on Sat May 26 14:21:45 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif
#include <wx/bitmap.h>

extern void initialize_images(void);

extern wxBitmap *_img_dashboard_tactics_pi; // if needed, separate icons can be created...
extern wxBitmap *_img_dashboard_tactics;    // ... if built-in dashboard has a copyright.
extern wxBitmap *_img_dial;
extern wxBitmap *_img_instrument;
extern wxBitmap *_img_minus;
extern wxBitmap *_img_plus;

#ifdef OCPN_USE_SVG
extern wxString _svg_dashboard_tactics;
extern wxString _svg_dashboard_tactics_rollover;
extern wxString _svg_dashboard_tactics_toggled;
#endif //  OCPN_USE_SVG

extern wxBitmap *bmpBtnStartRec;
extern wxBitmap *bmpBtnStopRec;
extern wxBitmap *bmpBtnBackstop;
extern wxBitmap *bmpBtnEject;

#endif /* ICONS_H */
